[global]
ioengine=/data/guntherxing/dev/spdk/build/fio/spdk_bdev
spdk_json_conf=/data/guntherxing/dev/spdk/exp/config/debug_ftl_op20.json
direct=1
iodepth=128
bs=4k
numjobs=1
thread=1
time_based=1
norandommap=1
log_flags=bdev
size=100%
filename=ftl0

[precondition]
name=precondition
rw=write
stonewall=1

[job1]
name=job1
rw=write
runtime=120s
ramp_time=60s
stonewall=1

[job2]
name=job2
rw=read
stonewall=1