[global]
ioengine=/home/xgj/spdk/build/fio/spdk_bdev
spdk_json_conf=/data/guntherxing/dev/spdk/exp/config/trace_sepbit_greedy_op20.json
direct=1
numjobs=1
thread=1
log_flags=bdev

[trace0]
iodepth=32
read_iolog=/home/xgj/tencent_dataset/subdataset0_0305.trace

[trace1]
iodepth=32
read_iolog=/home/xgj/tencent_dataset/subdataset1_0305.trace

[trace2]
iodepth=32
read_iolog=/home/xgj/tencent_dataset/subdataset2_0305.trace

[trace3]
iodepth=32
read_iolog=/home/xgj/tencent_dataset/subdataset3_0305.trace